sudo: required

language: php

services:
  - docker

cache:
  directories:
    - dgoss

install:
  # install goss and dgoss
  - mkdir -p $(pwd)/dgoss
  - curl -L https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dgoss/dgoss -o $(pwd)/dgoss/dgoss
  - chmod +rx $(pwd)/dgoss/dgoss
  - curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.4/goss-linux-amd64 -o $(pwd)/dgoss/goss-linux-amd64
  - export GOSS_PATH=$(pwd)/dgoss/goss-linux-amd64
  - export PATH=$(pwd)/dgoss:$PATH

script:
  - (cd images-build/nginx; sh ./test.sh)
  - (cd images-build/php-52-xdebug; sh ./test.sh)
  - (cd images-build/test-front; sh ./test.sh)

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  # setup the repo destinations
  - export NGINX_REPO=lucatume/nginx-for-wp
  - export PHP52_REPO=lucatume/php-52-xdebug
  - export TESTFRONT_REPO=lucatume/test-front
  # create the tag
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  # push the nginx repo
  - docker tag $NGINX_REPO $NGINX_REPO:$TAG
  - docker tag $NGINX_REPO $NGINX_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $NGINX_REPO  
  # push the PHP 5.2 repo
  - docker tag $PHP52_REPO $PHP52_REPO:$TAG
  - docker tag $PHP52_REPO $PHP52_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $PHP52_REPO  
  # push the test-front repo
  - docker tag $TESTFRONT_REPO $TESTFRONT_REPO:$TAG
  - docker tag $TESTFRONT_REPO $TESTFRONT_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $TESTFRONT_REPO
