sudo: required

language: php

services:
  - docker

cache:
  directories:
    - dgoss

install:
  # install goss and dgoss
  - mkdir -p $(pwd)/dgoss
  - curl -L https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dgoss/dgoss -o $(pwd)/dgoss/dgoss
  - chmod +rx $(pwd)/dgoss/dgoss
  - curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.4/goss-linux-amd64 -o $(pwd)/dgoss/goss-linux-amd64
  - export GOSS_PATH=$(pwd)/dgoss/goss-linux-amd64
  - export PATH=$(pwd)/dgoss:$PATH

script:
  - (cd images-build/nginx; sh ./test.sh)
  - (cd images-build/php-52-xdebug; sh ./test.sh)
  - (cd images-build/test-front; sh ./test.sh)
