#!/usr/bin/env bash
set -e

xdebugConfig="/usr/local/etc/php/conf.d/xdebug.ini"
opcacheConfig="/usr/local/etc/php/conf.d/opcache.ini"
memcacheConfig="/usr/local/etc/php/conf.d/memcache.ini"

# manage Xdebug configuration
remoteHost="127.0.0.1"
remotePort="9001"

if [[ $XDEBUG_REMOTE_HOST != "" ]]; then
	remoteHost="$XDEBUG_REMOTE_HOST"
fi

if [[ $XDEBUG_REMOTE_PORT != "" ]]; then
	remotePort="$XDEBUG_REMOTE_PORT"
fi

if [[ $XDEBUG_DISABLE == "1" ]]; then
	echo "XDebug disabled"
	sed -i'' "s/zend_extension/;zend_extension/g" $xdebugConfig
else
	echo "XDebug enabled"
	echo "XDebug remote host set to $remoteHost"
	echo "XDebug remote port set to $remotePort"
fi

sed -i'' "s/<<remoteHost>>/$remoteHost/g" $xdebugConfig
sed -i'' "s/<<remotePort>>/$remotePort/g" $xdebugConfig

# maybe disable OpCache
if [[ $OPCACHE_DISABLE == "1" ]]; then
	echo "OpCache disabled"
	sed -i'' 's/zend_extension/;zend_extension/g' $opcacheConfig;
fi

# maybe disable Memcache
if [[ $MEMCACHE_DISABLE == "1" ]]; then
	echo "Memcache disabled"
	sed -i'' 's/extension/;extension/g' $memcacheConfig;
fi

# if first arg is `-f` or `--some-option` call the php bin
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
elif [ "" == "$1" ]; then
	# if no command was provided start php fpm
	set -- php-cgi --fpm	
fi

exec "$@"