#!/usr/bin/env bash

# replace the remote_host in Xdebug configuration
xdebugConfig="/usr/local/etc/php/conf.d/xdebug.ini"

remoteHost="127.0.0.1"
remotePort="9001"

if [[ $XDEBUG_REMOTE_HOST != "" ]]; then
   echo "XDebug remote host will be set to $XDEBUG_REMOTE_HOST"
   remoteHost="$XDEBUG_REMOTE_HOST"
else
   echo "XDebug remote host will be set to $remoteHost"
fi

sed -i'' "s/<<remoteHost>>/$remoteHost/g" $xdebugConfig

if [[ $XDEBUG_REMOTE_PORT != "" ]]; then
   echo "XDebug remote port will be set to $XDEBUG_REMOTE_PORT"
   remoteHost="$XDEBUG_REMOTE_PORT"
else
   echo "XDebug remote port will be set to $remotePort"
fi

sed -i'' "s/<<remotePort>>/$remotePort/g" $xdebugConfig

php-cgi --fpm
