version: "2"

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
          - "80:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
    mysql:
        image: mysql 
        environment:
            - VIRTUAL_HOST=db.localhost
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${DOMAIN}
            - MYSQL_USER=${DOMAIN}
            - MYSQL_PASSWORD=${DOMAIN}
        volumes:
            - ./database:/var/lib/mysql
        ports:
            - "3306:3306"
        user: "1000"
    memcached:
        image: memcached:alpine
    php:
        environment:
            - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
        build: ./build/php
        links:
            - memcached
            - "mysql:db.localhost"
            - "nginx-proxy:${DOMAIN}.localhost"

        volumes:
            - ./www:/var/www/html
    nginx:
        build: ./build/nginx
        environment:
            - VIRTUAL_HOST=${DOMAIN}.localhost,*.${DOMAIN}.localhost
        volumes:
            - ./www:/var/www/html
        links:
            - php
