version: "2"

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./server/conf/nginx:/etc/nginx/vhost.d:ro
    mysql:
        image: mysql 
        environment:
            - VIRTUAL_HOST=db.localhost
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${DOMAIN}
            - MYSQL_USER=${DOMAIN}
            - MYSQL_PASSWORD=${DOMAIN}
        volumes:
            - ./server/database:/var/lib/mysql
        ports:
            - "3306:3306"
        user: "1000"
    memcached:
        image: memcached:alpine
    mailcatcher:
        image: helder/mailcatcher
        environment:
            - VIRTUAL_HOST=mailcatcher.localhost
    php:
        environment:
            - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
        build: ./server/build/php
        links:
            - memcached
            - "mysql:db.localhost"
            - "nginx-proxy:${DOMAIN}.localhost"
            - "mailcatcher:mail"
        volumes:
            - ./server/www:/var/www/html
    nginx:
        build: ./server/build/nginx
        environment:
            - VIRTUAL_HOST=${DOMAIN}.localhost,*.${DOMAIN}.localhost
        volumes:
            - ./server/www:/var/www/html
        links:
            - php
