#!/usr/bin/env bash
echo "What is the domain (e.g. 'app') of the project? Type it and press Enter.\n"

read domain

if [ ""  == $domain ]; then
	echo "Aborting: empty domains are not a thing."
	return -1
fi

for file in docker-compose.yml wp-cli.local.yml docker/www/index.php docker/build/nginx/conf.d/default.conf; do
	echo "Replacing in $file..."
    sed -i '' "s/{{domain}}/$domain/g" $(pwd)/$file
done

echo "Replacing in docker/www..."
find $(pwd)/docker/www -type f -exec \
    sed -i '' "s/{{domain}}/$domain/g" {} +

echo "Replacing in docker/build..."
find $(pwd)/docker/build -type f -exec \
    sed -i '' "s/{{domain}}/$domain/g" {} +

echo "Building images..."

docker-compose build

echo "Creating reverse proxy config files..."
mkdir -p docker/conf/nginx

nginxConf="client_max_body_size 100m;"

echo $nginxConf > "docker/conf/nginx/$domain.localhost"
