#!/usr/bin/env bash
set -e

conf="/etc/nginx/conf.d/default.conf"
virtualHost="wp.localhost"

if [[ $VIRTUAL_HOST != "" ]]; then
	virtualHost="$VIRTUAL_HOST"
fi

echo "Host set to $virtualHost"

sed -i'' "s/<<virtualHost>>/$virtualHost/g" $conf

# if first arg is `-f` or `--some-option` call the php bin
if [ "${1#-}" != "$1" ]; then
	set -- nginx "$@"
elif [ "" == "$1" ]; then
	# if no command was provided start php fpm
	set -- nginx -g 'daemon off;'
fi

exec "$@"
