#!/usr/bin/env bash
set -e

conf="/etc/nginx/conf.d/default.conf"
serverDomain="wp.localhost"

if [[ $serverDomain != "" ]]; then
	serverDomain="$serverDomain"
fi

echo "Host set to $serverDomain"

sed -i'' "s/<<serverDomain>>/$serverDomain/g" $conf

# if first arg is `-f` or `--some-option` call the php bin
if [ "${1#-}" != "$1" ]; then
	set -- nginx "$@"
elif [ "" == "$1" ]; then
	# if no command was provided start php fpm
	set -- nginx -g 'daemon off;'
fi

exec "$@"
