#!/usr/bin/env bash
set -e

xdebugConfig="/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
xdebugConfigParams="/usr/local/etc/php/conf.d/xdebug-conf.ini"
opcacheConfig="/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini"

# manage Xdebug configuration
remoteHost="127.0.0.1"
remotePort="9001"

if [[ $XDEBUG_REMOTE_HOST != "" ]]; then
	remoteHost="$XDEBUG_REMOTE_HOST"
fi

if [[ $XDEBUG_REMOTE_PORT != "" ]]; then
	remotePort="$XDEBUG_REMOTE_PORT"
fi

if [[ $XDEBUG_DISABLE == "1" ]]; then
	echo "XDebug disabled"
	sed -i'' "s/zend_extension/;zend_extension/g" $xdebugConfig
else
	echo "XDebug enabled"
	echo "XDebug remote host set to $remoteHost"
	echo "XDebug remote port set to $remotePort"
fi

sed -i'' "s/<<remoteHost>>/$remoteHost/g" $xdebugConfigParams
sed -i'' "s/<<remotePort>>/$remotePort/g" $xdebugConfigParams

# maybe disable OpCache
if [[ $OPCACHE_DISABLE == "1" ]]; then
	echo "OpCache disabled"
	sed -i'' 's/zend_extension/;zend_extension/g' $opcacheConfig;
fi

# add global Composer binaries location to the path
export PATH=/var/www/.composer/vendor/bin:$PATH

if [[ "bash" == "$@"  ]]; then
	# allow interactive mode in the container
	set -- /bin/bash
else
	# append the command to the codecept binary
	set -- codecept "$@"
fi

exec "$@"
